### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by Zatyri** [ni-eminen/eigenface#1]
## General notes
First, I would like to point out that I am unfamiliar with Jupiter notebooks (first time I am in contact with it) and any suggestions related to code structure and best practices might be totally off. 
I liked the picture of the algorithm in the description, as it made reading and understanding the code easier.
## Code structure
The code is clear and readable. Naming of variables is describing and follows python conventions. The code is however written in a long sequence. I would suggest that you break up your code into functions or classes and methods. This would improve the structure and readability of the code. Debugging and testing is also a lot easier with clearly defined and simple functions. 
You have done this in your helpers, that you apparently are not using anymore. This leads me to believe that you will take this approach for the main program.
It is better, in my experience, to use strongly typed approach with complex programs and algorithms. It might add some overhead, but it will make it easier to know expected types as the project grows. It also adds to the readability.
## Tests
There are to some extent test for the helpers file. The tests evaluate correct inputs, but some tests could be expanded to test some edge cases.  It could also be beneficial to test with invalid input. For example, what happens if you feed “test_sum_of_vectors” with different length lists. 
The main program lacks tests altogether and that’s not good. The main program is also hard to test because it is not divided into functions. 
## Documentation
I would have hoped for some instructions on how to run the program. Some documentation on the application architecture would also be nice.  The picture of the algorithm is good and clarifying, as previously mentioned.
## Closing notes
I really enjoyed familiarizing myself with eigenfaces concept, as it was a completely new thing for me. I think you have nailed the core of the algorithm, now its only optimizing and polishing. 

Keep up the good Work!

**Comment by ni-eminen** [comment]
Thanks for the comments!

Some clarifications:

> The code is however written in a long sequence. I would suggest that you break up your code into functions or classes and methods.

It's true the code is written in a long sequence, but this is actually convenient with Jupyter notebooks as they let you run each cell separately and in any order you'd like (after initially running them in order). So that's why I have not created separate methods,  instead, the code is grouped into cells. This seems to be the case with .ipynb in general when looking at other projects. Granted I'm no expert yet.

> It is better, in my experience, to use strongly typed approach with complex programs and algorithms.

Yes, I should use Python's typing system more efficiently.

> The tests evaluate correct inputs, but some tests could be expanded to test some edge cases. It could also be beneficial to test with invalid input. For example, what happens if you feed “test_sum_of_vectors” with different length lists.

This is true and a good point. I have replaced the functions with Numpy methods as it's not efficient to write the heavy lifting functionality in Python, so I'm likely deleting most of the helper methods.

> I would have hoped for some instructions on how to run the program. Some documentation on the application architecture would also be nice.

Instructions will be added soon! Since the program is very linear and non-interactive (aside from changing the dataset, there is no interaction), there has not been much of an architecture to document.

Thank you for the comments.
